# Explore trained models using Aphynity Framework


In [2]:
import torch
import torchdiffeq
import matplotlib.pyplot as plt

from utils import data_utils
from models import PendulumModel

In [26]:
# Load Model
model_path ='model.pt'
model = torch.load(open(model_path,'rb'))


In [27]:
model.state_dict()


OrderedDict([('omega', tensor([0.2750])),
             ('neural_net.neural_net.weight',
              tensor([[ 0.0545, -0.5359],
                      [-0.3801, -0.0104]]))])

In [28]:
t0 = 0.
te = 20.
T0 = 12
t = torch.linspace(t0, te, 40)

train,val,test = data_utils.get_pendulum_datasets(n=40,T0 = T0,alpha = 0.2)

init_state = train[:,0,:]


torch.sum(torch.linalg.norm(model.neural_net(t,train),dim=2)**2)

tensor(81.2668, grad_fn=<SumBackward0>)

In [36]:
torch.linalg.norm(model.neural_net(t,train),dim=2)**2 


tensor([[0.2661, 0.1846, 0.1456,  ..., 0.0092, 0.0072, 0.0060],
        [0.2383, 0.1778, 0.1423,  ..., 0.0088, 0.0070, 0.0045],
        [0.0847, 0.0939, 0.0912,  ..., 0.0020, 0.0026, 0.0029],
        ...,
        [0.2428, 0.2178, 0.2013,  ..., 0.0121, 0.0090, 0.0058],
        [0.2104, 0.1624, 0.1133,  ..., 0.0047, 0.0046, 0.0036],
        [0.0834, 0.0622, 0.0493,  ..., 0.0029, 0.0012, 0.0017]],
       grad_fn=<PowBackward0>)

In [37]:
(torch.linalg.norm(model.neural_net(t,train),dim=2)**2)

tensor([[0.5159, 0.4296, 0.3816,  ..., 0.0960, 0.0848, 0.0775],
        [0.4882, 0.4216, 0.3773,  ..., 0.0937, 0.0837, 0.0668],
        [0.2910, 0.3064, 0.3019,  ..., 0.0450, 0.0509, 0.0541],
        ...,
        [0.4928, 0.4667, 0.4487,  ..., 0.1099, 0.0947, 0.0763],
        [0.4586, 0.4030, 0.3366,  ..., 0.0684, 0.0681, 0.0602],
        [0.2888, 0.2494, 0.2221,  ..., 0.0538, 0.0346, 0.0415]],
       grad_fn=<CopyBackwards>)