# Explore trained models using Aphynity Framework


In [1]:
import torch
import torchdiffeq
import matplotlib.pyplot as plt

from utils import data_utils
from models import PendulumModel

In [6]:
# Load Model
model_path ='model.pt'
model = torch.load(open(model_path,'rb'))
model.state_dict()

OrderedDict([('omega', tensor(0.5949)),
             ('neural_net.neural_net.weight',
              tensor([[ 0.2976,  0.1669],
                      [-0.0665, -0.6182]]))])

OrderedDict([('omega', tensor(0.3921)),
             ('neural_net.neural_net.weight',
              tensor([[-0.5527,  0.4000],
                      [-0.3697,  0.0586]]))])

In [18]:
t0 = 0.
te = 20.
T0 = 12
t = torch.linspace(t0, te, 40)

batch_size = 800
train,val,test = data_utils.get_pendulum_datasets(n=batch_size ,T0 = T0,alpha = 0.2)

init_state = train[:,0,:]


torch.sum(torch.linalg.norm(model.neural_net(t,train),dim=2)**2) / batch_size

tensor(1.2875, grad_fn=<DivBackward0>)

In [17]:
model.neural_net(t,train).shape


torch.Size([800, 40, 2])

In [37]:
(torch.linalg.norm(model.neural_net(t,train),dim=2)**2)

tensor([[0.5159, 0.4296, 0.3816,  ..., 0.0960, 0.0848, 0.0775],
        [0.4882, 0.4216, 0.3773,  ..., 0.0937, 0.0837, 0.0668],
        [0.2910, 0.3064, 0.3019,  ..., 0.0450, 0.0509, 0.0541],
        ...,
        [0.4928, 0.4667, 0.4487,  ..., 0.1099, 0.0947, 0.0763],
        [0.4586, 0.4030, 0.3366,  ..., 0.0684, 0.0681, 0.0602],
        [0.2888, 0.2494, 0.2221,  ..., 0.0538, 0.0346, 0.0415]],
       grad_fn=<CopyBackwards>)